---
- hosts: deploy
  become: True
  vars:
    - openstack_release: 'liberty'
    - ubuntu_repo: 'http://mirror.cwb.cumulusnetworks.com/ubuntu/'
  tasks:
    - name: configure network interfaces
      copy: src=interfaces.deployserver dest=/etc/network/interfaces
      notify:
        - shutdown all ints
        - bring up all ints

    - name: flush stuff
      meta: flush_handlers

    # install the vlan package for bridging support
    # install lldp to verify connectivity to switch VM
    # install bridge-utils so that brctl works
    # install git for cloning OSAD repo
    # install pip for running pip requirements
    - name: install prereq packages
      apt: name={{ item }} update_cache=yes cache_valid_time=10000
      with_items:
        - vlan
        - lldpd
        - python-pip
        - git
        - vim
        - tmux


    - name: git clone osad repo
      git:
        repo: 'https://github.com/stackforge/os-ansible-deployment.git'
        dest: '/root/osad'
        version: "{{ openstack_release }}"
      ignore_errors: yes

    - name: run bootstrap ansible script
      shell: /root/osad/scripts/bootstrap-ansible.sh
      args:
        creates: /usr/local/bin/openstack-ansible
        chdir: '/root/osad'

    - name: copy openstack_deploy to /etc folder as recommended by Readme
      command: cp -r /root/osad/etc/openstack_deploy /etc/ creates=/etc/openstack_deploy

    - name: set the password for various openstack components to be password123
      replace:
        dest: '/etc/openstack_deploy/user_secrets.yml'
        regexp: '(.*password:\s*\n)'
        replace: '\1 password123\n'
        backup: 'yes'

    - name: set the tokens auth keys for various openstack components
      shell: ./scripts/pw-token-gen.py --file /etc/openstack_deploy/user_secrets.yml
      args:
        chdir: /root/osad

    - name: copy deploy ssh key to ansible server
      fetch:  src=/root/.ssh/id_rsa.pub dest=./deploy_key_id_rsa.pub flat=yes

    - name: copy openstack_user_config.yml from vagrant folder to deployment host
      copy: src=files/openstack_user_config.yml dest=/etc/openstack_deploy/

    - name: append caching apt repo lines for containers to use
      lineinfile: dest=/root/osad/playbooks/inventory/group_vars/hosts.yml line="{{item}}"
      with_items:
        - '# Apt repo for openstack containers to use'
        - "lxc_container_template_main_apt_repo: {{ ubuntu_repo }} "
        - "lxc_container_template_security_apt_repo: {{ ubuntu_repo }} "

    - name: increase ssh delay to help prevent ssh timeouts
      lineinfile: 'dest="/etc/openstack_deploy/user_variables.yml" line="ssh_delay: 20"'

    - name: disable keepalived in haproxy - not needed in vagrant setup
      lineinfile:
        dest: "/etc/openstack_deploy/user_variables.yml"
        regexp: "haproxy_use_keepalived"
        line: "haproxy_use_keepalived: False"


  handlers:
    - name: shutdown all ints
      command:  "/sbin/ifdown -X lo -X eth0 -a"
    - name: bring up all ints
      command: "/sbin/ifup -X lo -X eth0 -a"


