---
galaxy_info:
  author: elnappo <elnappoo@gmail.com>
  description: Install apt-cacher-ng
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - packaging

dependencies: []
