---
# tasks file for apt-cacher-ng
- name: Install apt-cacher-ng
  apt: name=apt-cacher-ng state=latest update_cache=yes cache_valid_time=3600

- name: Create CacheDir
  file: path={{ apt_cacher_ng_cache_dir }} owner=apt-cacher-ng group=apt-cacher-ng mode=2755 state=directory

- name: Set config
  lineinfile: dest=/etc/apt-cacher-ng/acng.conf regexp={{ item.regexp }} line="{{ item.line }}" state={{ item.state | default("present") }}
  with_items:
    - { regexp: "^Port:", line: "Port: {{ apt_cacher_ng_port }}" }
    - { regexp: "^CacheDir:\ ", line: "CacheDir: {{ apt_cacher_ng_cache_dir }}" }
  notify:
    - restart apt-cacher-ng

- name: Remove /etc/apt-cacher-ng/zz_debconf.conf
  file: path=/etc/apt-cacher-ng/zz_debconf.conf state=absent
  notify:
    - restart apt-cacher-ng

- name: Enable apt-cacher-ng on boot
  service: name=apt-cacher-ng state=started enabled=yes

- name: Allow apt-cacher-ng (Firewall)
  ufw: rule=allow port={{ apt_cacher_ng_port }} proto=tcp
  when: apt_cacher_ng_setup_ufw
